cherry-embedded/CherryUSB

class/cdc/usbh_cdc_acm.c, class/cdc/usbh_cdc_acm.h, class/hid/usbh_hid.c, class/hid/usbh_hid.h, class/msc/usbh_msc.c, class/msc/usbh_msc.h
host class driver struct 添加 hport 成员，方便引用。
=> update host class driver struct: add hport.

core/usbd_core.c
[usbd_get_descriptor]: handle USB_DESCRIPTOR_TYPE_OTHER_SPEED.
=> handle USB_DESCRIPTOR_TYPE_OTHER_SPEED

demo/phytium-e2000/usbhost/inc/usb_host.h, demo/phytium-e2000/usbhost/src/cmd_usb.c, demo/phytium-e2000/usbhost/src/usb_disk.c, port/xhci/usb_config.h, port/xhci/usb_hc_xhci.c, port/xhci/usb_hc_xhci.h, port/xhci/xhci_reg.h
update issue that reset mps by cmd_evaluate_context failed
configure hid ep failed not fixed
=> fix xhci update mps issue, add xhci dumpers, update e2000 demo

class/wireless/usbh_rndis.c
- fix buffer size and pointer error
=> class: rndis host: fix buffer size and pointer error

common/usb_util.h
- Added support for the IAR for risc-v toolchain
=> common: Add support for IAR for risc-v toolchain

port/ehci/usb_glue_hpm.c, port/ehci/usb_hc_ehci.c, port/hpm/usb_dc_hpm.c
- separate host and device USB instance config
=> port: hpmicro: separate host and device USB instance config

class/hub/usbh_hub.c, class/msc/usbd_msc.c, osal/usb_osal.h, osal/usb_osal_freertos.c, osal/usb_osal_rtthread.c, osal/usb_osal_yoc.c, third_party/FreeRTOS-10.4/rndis_host/rndis_host.c, third_party/rt-thread-4.1.1/rndis_host/rndis_host.c, third_party/rt-thread-4.1.1/rndis_host/rndis_host_lwip2.1.2.c
- add USB_OSAL_WAITING_FOREVER for Semaphore and Queue use
=> osal: add USB_OSAL_WAITING_FOREVER for Semaphore and Queue use

port/nuvoton/README.md, port/nuvoton/usb_dc_usbfs.c
测试代码https://github.com/xmaowu/cherryusb_nuvoton.git
=> Nuvoton 全速USB设备控制器 port

port/ehci/usb_glue_hpm.c, port/hpm/usb_dc_hpm.c
=> hpmicro: update port files

core/usbh_core.c, core/usbh_core.h, port/hpm/usb_dc_hpm.c
- usbh support riscv iar
- fix hpmicro usb_dc_deinit()
=> update for riscv-iar and hpmicro

cherryusb_config_template.h, class/msc/usbd_msc.c, class/msc/usbd_msc.h, core/usbd_core.c, demo/cdc_acm_hid_msc_template.c, demo/cdc_acm_msc_template.c, demo/msc_ram_template.c, demo/msc_storage_template.c
- increase endpoint number from 8 to 16
- msc device support multi lun
=> usbd: increase endpoint num and support msc multi lun

cherryusb_config_template.h, core/usbd_core.c, core/usbh_core.c, port/hpm/usb_dc_hpm.c
- update endpoint number usage and fix busid check
- HPMicro: port: fix _dcd_data align to 2048
=> update for multi port

port/ehci/usb_glue_hpm.c, port/hpm/usb_dc_hpm.c
- decoupling the relationship between busid and usbid
=> port: HPMicro: decoupling the relationship between busid and usbid

port/hpm/usb_dc_hpm.c
=> port: HPMicro: fix transfer_len not reset

class/msc/usbd_msc.c
- stage change should be before usbd_ep_start_write()
=> class: msc: stage change should be before usbd_ep_start_write()

port/hpm/usb_dc_hpm.c
- call suspend/connect/disconnect event
=> port: HPMicro: call suspend/connect/disconnect event

port/hpm/usb_dc_hpm.c
- fix usbd_ep_close() not reset ep_enable flag
=> HPMicro: port: fix usbd_ep_close() not reset ep_enable flag

osal/usb_osal_freertos.c
=> osal: freeRTOS: fix enter/exit critical

port/hpm/usb_dc_hpm.c
- update hpm usb deivce port file
=> port: HPMicro: update hpm usb deivce port file

port/ehci/usb_glue_hpm.c
=> port: HPMicro: update usb_glue_hpm

class/video/usb_video.h, demo/video_static_h264_template.c, demo/video_static_mjpeg_template.c, demo/video_static_yuyv_template.c
Use usb endpoint descriptor initialization macro in video demo
=> video demo update

port/musb/usb_dc_musb.c
fix bug：usbd_ep_is_stalled api err.
=> fix(port/musb/usb_dc_musb.c): usbd_ep_is_stalled api err.

port/ehci/usb_hc_ehci.c
=> port: ehci: update init and deinit

core/usbd_core.c, core/usbd_core.h
- add usb_device_is_suspend() API
=> usbd_core: add usb_device_is_suspend() API
